### ISSUE TITLE
Consider changing license to EPL-2.0 with secondary license(s)

### ISSUE THREAD

**Issue by ssoloff** [rherrmann/junit5-experiments#1]
Greetings @rherrmann,

Thanks for the code you've contributed in this repo.  My team recently switched to JUnit 5 and would like to use some of your extensions until equivalent functionality is available in JUnit 5 proper.  AFAIK, these extensions only have a source distribution, which would require us to copy the sources into our codebase.  However, our code is licensed under GPL-2.0-or-later, which is [incompatible](https://www.gnu.org/licenses/license-list.en.html#EPL) with EPL-1.0.

Would you consider changing the license for this repo to EPL-2.0 with GPL-2.0-or-later as a designated secondary license?  Per the [EPL-2.0](https://www.eclipse.org/legal/epl-2.0/), granting use of a secondary license must be explicit:

> #### Exhibit A - Form of Secondary Licenses Notice
>
> > “This Source Code may also be made available under the following Secondary Licenses when the conditions for such availability set forth in the Eclipse Public License, v. 2.0 are satisfied: {name license(s), version(s), and exceptions or additional permissions here}.”
>
> Simply including a copy of this Agreement, including this Exhibit A is not sufficient to license the Source Code under Secondary Licenses.
>
> If it is not possible or desirable to put the notice in a particular file, then You may include the notice in a location (such as a LICENSE file in a relevant directory) where a recipient would be likely to look for such a notice.
>
> You may add additional accurate notices of copyright ownership.

Note that JUnit 5 [switched to EPL-2.0](https://github.com/junit-team/junit5/issues/1045) just before the GA release late last year, but it doesn't appear they designated any secondary licenses.  This doesn't concern us as much because we can add an exception for this library to the GPL that covers our test code.  However, we're not sure such an exception is permissible when including GPL-incompatible sources directly.  Hence, the motivation for creating this issue. :smile:

**Comment by rherrmann** [comment]
I am glad to see that you find the code in this repository useful. If you open a pull request with the necessary changes I will approve it as soon as I find time (i.e. may take a few days).

**Comment by ssoloff** [comment]
Many thanks, @rherrmann.  I should be able to put together a PR within a few days.
